# example netlify.toml
[build]
  command = "nuxt generate"
  functions = "netlify/functions"
  publish = "dist"

#[build]
#  command = "npm run build"
#  publish = "dist"
#  functions = "netlify/functions"

